### ISSUE TITLE
Mid Fi Prototype - First Aid

### ISSUE THREAD

**Issue by zehuac2** [Zehua-Chen/coms4170-ui-project#3]
# Overview

Complete the mid-fi prototype

# Todos

- [x] Add a progress bar to reminds users how far he/she gets
- [x] Make the icon on the quiz page clickable and direct users to the related knowledge page
- [x] Make the quiz questions draggable and droppable
- [x] Make the knowledge page more interactive by making the icon clickable
