### ISSUE TITLE
Prepare Presentation

### ISSUE THREAD

**Issue by zehuac2** [Zehua-Chen/coms4170-ui-project#4]
# Overview

Finish [the slides](https://docs.google.com/presentation/d/1IoW5UL4PsnKdKXN-DDD9ChEdA9l9ef9B0Uaad9euSmc/edit?usp=sharing)

# Tasks

- [x] Add overview
- [x] Add both prototypes
- [x] Add user test results
- [ ] Add votes of each team member
