### ISSUE TITLE
Homework 11 Warmup

### ISSUE THREAD

**Issue by zehuac2** [Zehua-Chen/coms4170-ui-project#6]
# Tasks

- [x] Choose a prototype to continue working on
- [ ] Final prototype iteration
- [x] Github repo
  - [ ] Screenshot of collaborators
- [x] Job assignment
