### ISSUE TITLE
Result Page Modifications

### ISSUE THREAD

**Issue by zehuac2** [Zehua-Chen/coms4170-ui-project#9]
# Tasks

- [x] The total score is wrong, only 6 questions
- [x] Use tables for the result page
- [x] Use color for right and wrong
- [x] Use modal to show preview
- [x] Use links to direct the user to relevant questions

**Comment by Zehua-Chen** [comment]
Pr: #12
